// Generate source-backed runtime templates, never from caller-supplied deployment code.
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import * as E from '../../2026-09-04-mvp-rehearsal/node_modules/ethers/lib.esm/index.js';
const root=fileURLToPath(new URL('../',import.meta.url));
const solc=process.env.EFS21_SOLC??`${process.env.HOME}/Library/Application Support/svm/0.8.30/solc-0.8.30`;
const choices={current:null,'baseline-7db38cd':'7db38cd','forced-code':'7db38cd-forced-code','forced-words':'7db38cd-forced-words','baseline-f43501a':'f43501a','baseline-58e61c4':'58e61c4','baseline-aa6b1b6':'aa6b1b6','baseline-bf566dc':'bf566dc','baseline-c088363':'c088363','integrity-c088363':'c088363-read-integrity'};
const catalogs={};
for(const [selection,fixture] of Object.entries(choices)){
  const frozenPath=root+`contracts/test/fixtures/source-graph-${fixture}.json`;
  if(fixture&&existsSync(frozenPath)){catalogs[selection]=JSON.parse(readFileSync(frozenPath));continue;}
  const kernel=JSON.parse(readFileSync(root+(fixture?`contracts/test/fixtures/native-kernel-${fixture}.json`:'contracts/out/NativeKernel.sol/NativeKernel.json')));
  const sources={};
  for(const [path,pin] of Object.entries(kernel.metadata.sources)){
    let content;
    if(fixture){
      const r=spawnSync('git',['show',`${kernel.sourceCommit}:Reviews/2026-09-11-efs21-pragmatic/contracts/${path}`],{cwd:root,encoding:'utf8'});
      assert.equal(r.status,0,r.stderr);content=r.stdout;
      for(const d of kernel.sourceDelta??[])if(d.path===path){assert.equal(content.split(d.before).length,2);content=content.replace(d.before,d.after);}
    }else content=readFileSync(root+'contracts/'+path,'utf8');
    assert.equal(E.keccak256(E.toUtf8Bytes(content)),pin.keccak256,path);
    sources[path]={content};
  }
  const {compilationTarget,...settings}=kernel.metadata.settings;
  settings.outputSelection={'*':{'*':['abi','evm.deployedBytecode','evm.bytecode','metadata'],'':['ast']}};
  const r=spawnSync(solc,['--standard-json'],{input:JSON.stringify({language:'Solidity',sources,settings}),encoding:'utf8',timeout:120000,maxBuffer:32*1024*1024});
  assert.equal(r.status,0,r.stderr);const output=JSON.parse(r.stdout);
  assert(!(output.errors??[]).some(e=>e.severity==='error'),JSON.stringify(output.errors));
  const [targetPath,targetName]=Object.entries(compilationTarget)[0];
  assert.equal('0x'+output.contracts[targetPath][targetName].evm.bytecode.object,kernel.bytecode.object,'exact selected constructor reproduced');
  const immutableNames={};
  for(const source of Object.values(output.sources))for(const c of source.ast.nodes.filter(n=>n.nodeType==='ContractDefinition'))for(const n of c.nodes)if(n.mutability==='immutable')immutableNames[n.id]=n.name;
  const templates={};
  for(const [path,contracts] of Object.entries(output.contracts))for(const [name,a] of Object.entries(contracts)){
    if(!a.evm.deployedBytecode.object)continue;
    const refs=a.evm.deployedBytecode.immutableReferences??{};
    templates[name]={runtime:'0x'+a.evm.deployedBytecode.object,immutables:Object.fromEntries(Object.entries(refs).map(([id,locations])=>{assert(immutableNames[id],id);return [immutableNames[id],locations]}))};
  }
  const profile={selection,split:selection==='current',targetName,compiler:kernel.metadata.compiler,settings:kernel.metadata.settings,sources:kernel.metadata.sources,...(fixture?{sourceCommit:kernel.sourceCommit,sourceDelta:kernel.sourceDelta??[]}:{}),templates};
  profile.id=E.keccak256(E.toUtf8Bytes(JSON.stringify(profile)));
  if(fixture)writeFileSync(frozenPath,JSON.stringify(profile,null,2)+'\n');
  catalogs[selection]=profile;
  console.log(`${selection}: exact constructor and ${Object.keys(templates).length} source-backed templates`);
}
writeFileSync(root+'sdk/source-graphs.mjs','// Generated by scripts/compile-graphs.mjs from exact source/compiler pins.\nexport const SOURCE_GRAPHS = '+JSON.stringify(catalogs)+';\n');
