#!/usr/bin/env node
// Aggregate every retained run under the evidence directory into
// tables.md (markdown tables computed ONLY from analysis.json files) and
// index.json (every file, its size, sha256 and the command that produced it).
//
//   node scripts/measure/report.mjs [--out evidence/gas-2026-09-10]
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const MVP = fileURLToPath(new URL('../../', import.meta.url));
const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : dflt; };
const OUT = resolve(MVP, opt('--out', 'evidence/gas-2026-09-10'));
const read = p => JSON.parse(readFileSync(p, 'utf8'));
const fmt = n => typeof n === 'number' ? n.toLocaleString('en-US') : String(n);
const pct = (a, b) => b ? (100 * a / b).toFixed(1) + '%' : '';

const runs = readdirSync(OUT).filter(d => /^run\d+$/.test(d) && existsSync(join(OUT, d, 'summary.json'))).sort((a, b) => Number(a.slice(3)) - Number(b.slice(3)));
const data = runs.map(r => {
  const summary = read(join(OUT, r, 'summary.json'));
  const environment = read(join(OUT, r, 'environment.json'));
  const ops = summary.operations.map(o => ({ ...o, analysis: read(join(OUT, r, o.op, 'analysis.json')) }));
  return { run: r, summary, environment, ops };
});

const lines = [];
const h = (level, text) => { lines.push('', '#'.repeat(level) + ' ' + text, ''); };
const table = (header, rows) => { lines.push('| ' + header.join(' | ') + ' |', '| ' + header.map(() => '---').join(' | ') + ' |'); for (const r of rows) lines.push('| ' + r.join(' | ') + ' |'); lines.push(''); };

lines.push('# Gas baseline tables (generated)', '', 'Generated by `node scripts/measure/report.mjs` from the analysis.json files under `' + relative(MVP, OUT) + '`. Every number is MEASURED from a retained artifact unless the column says ESTIMATED. Do not edit by hand.', '');

h(2, 'Runs');
table(['run', 'sequence', 'commit', 'dirty tree', 'anvil', 'solc', 'started', 'operations'],
  data.map(d => [d.run, d.summary.sequence, (d.environment.git.commit ?? '').slice(0, 12), String(d.environment.git.dirty), d.environment.versions.anvil.replace('anvil Version: ', ''), d.environment.versions.solc.version, d.environment.startedAt, d.ops.map(o => o.op).join(', ')]));

h(2, 'Receipt gas by operation and run (determinism)');
const opIds = [...new Set(data.flatMap(d => d.ops.map(o => o.op)))];
table(['operation', ...runs.map(r => r + ' receipt'), 'runs agree', ...runs.map(r => r + ' calldata zero/nonzero bytes')],
  opIds.map(id => { const rs = data.map(d => d.ops.find(o => o.op === id)); const vals = rs.map(o => o?.receiptGasUsed).filter(v => v !== undefined); return [id, ...rs.map(o => o ? fmt(o.receiptGasUsed) : ''), vals.length > 1 ? String(new Set(vals).size === 1) : 'n/a', ...rs.map(o => o ? o.analysis.intrinsic.zeroBytes + '/' + o.analysis.intrinsic.nonzeroBytes : '')]; }));

for (const d of data) {
  h(2, `${d.run} (${d.summary.sequence})`);
  for (const o of d.ops) {
    const a = o.analysis;
    h(3, `${d.run} / ${o.op} — receipt ${fmt(a.receiptGasUsed)}`);
    lines.push(a.note, '', `tx \`${a.txHash}\` block ${a.blockNumber} to ${a.toName ?? a.to}; ${fmt(a.execution.steps)} EVM steps; artifacts: \`${d.run}/${o.op}/{receipt,tx,prestate-diff,calltree,storage-ops,analysis}.json\`, \`trace.json.gz\` (${fmt(a.artifacts.rawTraceBytes)} raw bytes).`, '');
    lines.push('**Reconciliation (components sum to the receipt).**', '');
    const c = a.categories;
    const rows = [
      ['intrinsic: 21,000 base', 21000, ''], ['intrinsic: calldata (4/zero, 16/nonzero) — ' + a.intrinsic.zeroBytes + ' zero + ' + a.intrinsic.nonzeroBytes + ' nonzero bytes', a.intrinsic.calldataGas, ''],
      ...['SSTORE', 'SLOAD', 'KECCAK256', 'LOG', 'CALLDATA', 'MEMORY', 'STACK', 'CONTROL', 'ARITH', 'CODE', 'ENV', 'OTHER', 'CALL_OVERHEAD', 'PRECOMPILE'].map(k => [k + ' (' + fmt(a.categoryCounts[k]) + ' ops)', c[k], pct(c[k], a.execution.gross)]),
      ['execution gross (sum of categories)', a.execution.gross, a.execution.categoriesMatchGross ? 'matches trace gas delta' : 'MISMATCH vs trace gas delta ' + fmt(a.execution.gross)],
      ['refund applied (EIP-3529, cap ' + fmt(a.refund.cap) + ')', -a.refund.applied, 'node counter ' + fmt(a.refund.nodeCounter) + ', model ' + fmt(a.refund.model)],
      ['**receipt gasUsed**', a.receiptGasUsed, 'residual ' + fmt(a.reconciliation.residual)],
    ];
    table(['component', 'gas', 'share of gross / check'], rows.map(r => [r[0], fmt(r[1]), r[2]]));
    lines.push(`EIP-7623 floor would be ${fmt(a.intrinsic.floor7623)} (not active: hardfork ${a.intrinsic.hardfork}). Intrinsic from trace (gasLimit − first-step gas) = ${fmt(a.intrinsic.fromTrace)} (${a.intrinsic.matches ? 'matches' : 'MISMATCH'}).`, '');
    lines.push('**Checks.** ' + Object.entries(a.checks).filter(([k]) => k !== 'frameMismatchDetail').map(([k, v]) => `${k}=${v}`).join(', ') + '.', '');
    lines.push('**Gas by contract (self gas, call overhead booked to the caller).**', '');
    table(['contract', 'gas', 'share', 'steps'], Object.entries(a.byContract).map(([n, v]) => [n, fmt(v.gas), pct(v.gas, a.execution.gross), fmt(v.n)]));
    lines.push('**SSTORE census.** ' + fmt(a.sstore.sstoreOps) + ' SSTOREs over ' + fmt(a.sstore.distinctSlotsWritten) + ' distinct slots; ' + a.sstore.modelMismatches + ' deviations from the EIP-2200/2929 cost model; ' + a.checks.unattributedWrites + ' unattributed writes.', '');
    const wc = a.sstore.writesByClass, gc = a.sstore.gasByClass;
    table(['write class', 'SSTOREs', 'gas', 'definition'], [
      ['FRESH', wc.FRESH ?? 0, gc.FRESH ?? 0, 'original 0, first write, nonzero value (20,000 + 100 warm / 2,100 cold access)'],
      ['COLD_REWRITE', wc.COLD_REWRITE ?? 0, gc.COLD_REWRITE ?? 0, 'original nonzero, first write in tx, different nonzero value (2,900 + access)'],
      ['WARM_REWRITE', wc.WARM_REWRITE ?? 0, gc.WARM_REWRITE ?? 0, 'slot already written in this tx, different value (100)'],
      ['NOOP', wc.NOOP ?? 0, gc.NOOP ?? 0, 'value equals current value (100); includes zero written to a zero slot'],
      ['CLEAR', wc.CLEAR ?? 0, gc.CLEAR ?? 0, 'nonzero to zero (refund 4,800)'],
      ['RESTORE', wc.RESTORE ?? 0, gc.RESTORE ?? 0, 'dirty slot written back to its original value'],
    ].map(r => [r[0], fmt(r[1]), fmt(r[2]), r[3]]));
    const sc = a.sstore.slotsByFinalClass;
    table(['distinct slot final class', 'slots'], [['FRESH (0 → nonzero)', sc.FRESH ?? 0], ['REWRITE (nonzero → different nonzero)', sc.REWRITE ?? 0], ['CLEARED (nonzero → 0)', sc.CLEARED ?? 0], ['UNCHANGED (nonzero, same value)', sc.UNCHANGED ?? 0], ['UNCHANGED_ZERO (zero written to zero)', sc.UNCHANGED_ZERO ?? 0]].map(r => [r[0], fmt(r[1])]));
    lines.push('**Slots by StateStore family (Kind) and final class.** Counts and Bootstrap are the kernel\'s non-journal structs (`s.count`, `s.init`); Authority is the U3 principal nonce; ChunkStatus/Chunk are the carrier.', '');
    const kinds = Object.entries(a.sstore.census).sort((x, y) => y[1].gas - x[1].gas);
    table(['Kind', 'slots', 'FRESH', 'REWRITE', 'CLEARED', 'UNCHANGED', 'UNCHANGED_ZERO', 'SSTOREs', 'SSTORE gas', 'write classes'], kinds.map(([k, v]) => [k, fmt(v.slots), fmt(v.FRESH), fmt(v.REWRITE), fmt(v.CLEARED), fmt(v.UNCHANGED), fmt(v.UNCHANGED_ZERO), fmt(v.writes), fmt(v.gas), Object.entries(a.sstore.writesByKindClass[k] ?? {}).map(([c, n]) => c + '=' + n).join(' ')]));
    const fam = {};
    for (const w of a.writes) if (w.kind === 'Posting' || w.kind === 'Word' || w.kind === 'PostingKey') { const f = w.family ?? (w.kind === 'PostingKey' ? 'n/a' : '?'); const k = 'family ' + f; const b = fam[k] ?? { Posting: 0, Word: 0, PostingKey: 0, FRESH: 0, other: 0 }; b[w.kind]++; if (w.class === 'FRESH') b.FRESH++; else b.other++; fam[k] = b; }
    if (Object.keys(fam).length) {
      lines.push('**Posting-index writes by IndexKeys family** (1 all-of-type, 2 type-unique, 3 record occurrences, 4 by-principal, 5 references-to-target, 6 typed-role→target, 7 scalar field index, 8 binding history, 10 binding scope; `?` = no preimage found).', '');
      table(['family', 'Posting head writes', 'Word writes', 'PostingKey writes', 'FRESH writes', 'other writes'], Object.entries(fam).sort().map(([k, v]) => [k, fmt(v.Posting), fmt(v.Word), fmt(v.PostingKey), fmt(v.FRESH), fmt(v.other)]));
    }
    lines.push('**SLOAD by Kind.** ' + fmt(a.sload.ops) + ' SLOADs (' + fmt(a.sload.coldOps) + ' cold, ' + fmt(a.sload.warmOps) + ' warm) over ' + fmt(a.sload.distinctSlots) + ' distinct slots, ' + fmt(a.sload.gas) + ' gas.', '');
    table(['Kind', 'distinct slots', 'reads', 'gas'], Object.entries(a.sload.byKind).sort((x, y) => y[1].gas - x[1].gas).map(([k, v]) => [k, fmt(v.distinctSlots), fmt(v.reads), fmt(v.gas)]));
    const g = a.sstore.glamsterdam;
    lines.push(`**Glamsterdam-style extrapolation (ESTIMATED).** FRESH ${g.freshWrites} × 110,020 + COLD_REWRITE ${g.coldRewrites} × 12,100 + warm (WARM_REWRITE+NOOP+RESTORE) ${g.warmWrites} × 10,100 = ${fmt(g.sstoreEstimate)} for the SSTORE component alone (CLEAR writes: ${g.clears}). Multipliers supplied by the PM; MEASURED counts, ESTIMATED product.`, '');
  }
}
writeFileSync(join(OUT, 'tables.md'), lines.join('\n') + '\n');

// index.json — every retained file with sha256 and producer.
const files = [];
(function walk(dir) { for (const e of readdirSync(dir, { withFileTypes: true })) { const p = join(dir, e.name); if (e.isDirectory()) walk(p); else files.push(p); } })(OUT);
const producer = rel => {
  const m = rel.match(/^(run\d+)\//);
  if (m) { const env = data.find(d => d.run === m[1])?.environment; return `node scripts/measure/baseline.mjs --run ${m[1].slice(3)} --sequence ${env?.sequence ?? '?'}`; }
  if (rel === 'tables.md' || rel === 'index.json') return 'node scripts/measure/report.mjs';
  return 'unknown';
};
const describe = rel => {
  const base = rel.split('/').pop();
  return ({ 'receipt.json': 'eth_getTransactionReceipt', 'tx.json': 'eth_getTransactionByHash (calldata, gas limit, access list)', 'trace.json.gz': 'gzip of the raw debug_traceTransaction structLogs response (stack enabled, memory/storage disabled)', 'prestate-diff.json': 'debug_traceTransaction prestateTracer diffMode', 'calltree.json': 'debug_traceTransaction callTracer', 'storage-ops.json': 'every SSTORE/SLOAD step (index, depth, slot, value) extracted from the trace', 'analysis.json': 'derived reconciliation, categories, SSTORE classification, Kind attribution, checks', 'environment.json': 'versions, node args, git revision, addresses', 'summary.json': 'per-run summary of every operation', 'store-keys.json': 'StateStore ordinal indexes enumerated at the final block (key universe for attribution)', 'posting-key-labels.json': 'posting key -> IndexKeys family preimage labels', 'tables.md': 'generated markdown tables', 'index.json': 'this index' })[base] ?? '';
};
const index = { generatedAt: new Date().toISOString(), root: relative(MVP, OUT), files: files.map(p => { const rel = relative(OUT, p); const buf = readFileSync(p); return { path: rel, bytes: buf.length, sha256: rel === 'index.json' ? null : createHash('sha256').update(buf).digest('hex'), producedBy: producer(rel), description: describe(rel) }; }).filter(f => f.path !== 'index.json') };
index.files.push({ path: 'index.json', bytes: null, sha256: null, producedBy: 'node scripts/measure/report.mjs', description: 'this index (hash not self-referential)' });
writeFileSync(join(OUT, 'index.json'), JSON.stringify(index, null, 2) + '\n');
console.log('wrote', join(OUT, 'tables.md'), 'and index.json with', index.files.length, 'files');
