#!/usr/bin/env node
// Two retained runs side by side (mode-1 minus mode-0), computed ONLY from
// their summary.json / analysis.json. Prints markdown; writes nothing.
//   node scripts/compare.mjs --a n1000-mode0 --b n1000-mode1
import { readFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { LAB } from './lab-fixture.mjs';

const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : dflt; };
const A = opt('--a', 'n1000-mode0'), B = opt('--b', 'n1000-mode1');
const read = p => JSON.parse(readFileSync(p, 'utf8'));
const load = label => { const out = resolve(LAB, 'evidence/' + label); const summary = read(join(out, 'summary.json')); const env = read(join(out, 'environment.json')); return { label, out, env, ops: new Map(summary.operations.map(o => [o.op, { ...o, analysis: existsSync(join(out, o.op, 'analysis.json')) ? read(join(out, o.op, 'analysis.json')) : null }])) }; };
const a = load(A), b = load(B);
const fmt = n => typeof n === 'number' && Number.isFinite(n) ? Math.round(n).toLocaleString('en-US') : String(n);
const f1 = n => (Math.round(n * 10) / 10).toLocaleString('en-US');
const signed = n => (n > 0 ? '+' : '') + fmt(n);
const lines = [];
const table = (header, rows) => { lines.push('| ' + header.join(' | ') + ' |', '| ' + header.map(() => '---').join(' | ') + ' |'); for (const r of rows) lines.push('| ' + r.join(' | ') + ' |'); lines.push(''); };
const hookSelf = o => o?.analysis?.byContract?.['IndexedAdmission (hook)']?.gas ?? null;
const moduleSelf = o => o?.analysis?.byContract?.['IndexLayerModule']?.gas ?? null;
lines.push('# Compare `' + A + '` (stored scopeLayout ' + (a.env.world?.storedScopeLayout ?? 'not recorded') + ') vs `' + B + '` (stored scopeLayout ' + (b.env.world?.storedScopeLayout ?? 'not recorded') + ')', '', 'Generated by `node scripts/compare.mjs --a ' + A + ' --b ' + B + '`; every number MEASURED from the two runs\' retained analysis.json; deltas are B − A.', '');

function perEntry(run, aId, bId) {
  const x = run.ops.get(aId), y = run.ops.get(bId); if (!x || !y) return null;
  const nx = Number(aId.split('-')[1]), ny = Number(bId.split('-')[1]), dn = ny - nx;
  const kinds = new Set([...Object.keys(x.sload.byKind), ...Object.keys(y.sload.byKind)]);
  const rows = {}; for (const k of kinds) { const rx = x.sload.byKind[k] ?? { reads: 0, gas: 0 }, ry = y.sload.byKind[k] ?? { reads: 0, gas: 0 }; rows[k] = { reads: (ry.reads - rx.reads) / dn, gas: (ry.gas - rx.gas) / dn }; }
  const cat = Object.fromEntries(Object.keys(y.categories).map(c => [c, (y.categories[c] - x.categories[c]) / dn]));
  return { rows, cat, receipt: (y.receiptGasUsed - x.receiptGasUsed) / dn, gross: (y.gross - x.gross) / dn, sloads: (y.sload.ops - x.sload.ops) / dn, sloadGas: (y.sload.gas - x.sload.gas) / dn, fixed: x.receiptGasUsed - nx * (y.receiptGasUsed - x.receiptGasUsed) / dn };
}
lines.push('## Backfill per entry (64 → 128 delta)', '');
const pa = perEntry(a, 'backfill-64', 'backfill-128'), pb = perEntry(b, 'backfill-64', 'backfill-128');
if (pa && pb) {
  table(['', A, B, 'delta (B − A)'], [
    ['receipt gas per entry', fmt(pa.receipt), fmt(pb.receipt), signed(pb.receipt - pa.receipt) + ' (' + (100 * (pb.receipt - pa.receipt) / pa.receipt).toFixed(1) + '%)'],
    ['execution gross per entry', fmt(pa.gross), fmt(pb.gross), signed(pb.gross - pa.gross)],
    ['SLOADs per entry', f1(pa.sloads), f1(pb.sloads), signed(pb.sloads - pa.sloads)],
    ['SLOAD gas per entry', fmt(pa.sloadGas), fmt(pb.sloadGas), signed(pb.sloadGas - pa.sloadGas)],
    ['implied fixed cost per call', fmt(pa.fixed), fmt(pb.fixed), signed(pb.fixed - pa.fixed)],
    ...Object.keys(pb.cat).filter(c => Math.abs(pa.cat[c] ?? 0) >= 1 || Math.abs(pb.cat[c]) >= 1).map(c => ['category ' + c + ' per entry', fmt(pa.cat[c] ?? 0), fmt(pb.cat[c]), signed(pb.cat[c] - (pa.cat[c] ?? 0))]),
  ]);
  const kinds = [...new Set([...Object.keys(pa.rows), ...Object.keys(pb.rows)])].filter(k => Math.abs(pa.rows[k]?.reads ?? 0) > 1e-9 || Math.abs(pb.rows[k]?.reads ?? 0) > 1e-9).sort((x, y) => ((pa.rows[y]?.gas ?? 0) + (pb.rows[y]?.gas ?? 0)) - ((pa.rows[x]?.gas ?? 0) + (pb.rows[x]?.gas ?? 0)));
  table(['StateStore kind read', A + ' SLOADs/entry', A + ' gas/entry', B + ' SLOADs/entry', B + ' gas/entry', 'gas delta'], kinds.map(k => [k, f1(pa.rows[k]?.reads ?? 0), fmt(pa.rows[k]?.gas ?? 0), f1(pb.rows[k]?.reads ?? 0), fmt(pb.rows[k]?.gas ?? 0), signed((pb.rows[k]?.gas ?? 0) - (pa.rows[k]?.gas ?? 0))]));
}
lines.push('## Chunks and the largest chunk under 16,777,216', '');
const chunkIds = run => [...run.ops.keys()].filter(k => /^backfill-(\d+)$/.test(k)).sort((x, y) => Number(x.split('-')[1]) - Number(y.split('-')[1]));
table(['chunk', A + ' receipt', A + ' per entry', B + ' receipt', B + ' per entry', 'per-entry delta'], [...new Set([...chunkIds(a), ...chunkIds(b)])].map(id => { const n = Number(id.split('-')[1]); const x = a.ops.get(id), y = b.ops.get(id); return [id, x ? fmt(x.receiptGasUsed) : '—', x ? fmt(x.receiptGasUsed / n) : '—', y ? fmt(y.receiptGasUsed) : '—', y ? fmt(y.receiptGasUsed / n) : '—', x && y ? signed(y.receiptGasUsed / n - x.receiptGasUsed / n) : '—']; }));
const landed = run => run.env.maxChunk.attempts.filter(t => t.status === '0x1').map(t => t.maxEntries + ' (' + fmt(t.gasUsed) + ')').join(', ') || 'none';
const failed = run => run.env.maxChunk.attempts.filter(t => t.status !== '0x1').map(t => t.maxEntries + ' (' + fmt(t.gasUsed) + ' consumed)').join(', ') || 'none';
lines.push('Largest chunk that landed: ' + A + ' → ' + landed(a) + '; failed attempts ' + failed(a) + '. ' + B + ' → ' + landed(b) + '; failed attempts ' + failed(b) + '.', '');
lines.push('## Hook (frame self gas of IndexedAdmission), reads, coverage init, declare', '');
const ids = ['u4-placement-1', 'hook-placement-fresh-word', 'hook-placement-warm-word', 'hook-placement-second-bucket', 'hook-remove-clear', 'hook-restore-set', 'hook-rebind-field-change', 'hook-rebind-uncovered', 'coverage-init', 'coverage-init-2', 'declare', 'probe-hit', 'probe-miss-covered', 'probe-tail-miss', 'probe-tolerated', 'probe-uncovered-revert', 'page-hot-256', 'page-hot-512', 'page-sparse', 'backfill-sparse-' + a.env.sparse, 'u4-upgrade'];
table(['op', A + ' receipt', B + ' receipt', 'receipt delta', A + ' hook self', B + ' hook self', 'hook delta', A + ' module self', B + ' module self', 'module delta', A + ' SLOADs', B + ' SLOADs'], ids.filter(id => a.ops.has(id) || b.ops.has(id)).map(id => { const x = a.ops.get(id), y = b.ops.get(id); const hx = hookSelf(x), hy = hookSelf(y), mx = moduleSelf(x), my = moduleSelf(y); return [id, x ? fmt(x.receiptGasUsed) : '—', y ? fmt(y.receiptGasUsed) : '—', x && y ? signed(y.receiptGasUsed - x.receiptGasUsed) : '—', hx === null ? '—' : fmt(hx), hy === null ? '—' : fmt(hy), hx !== null && hy !== null ? signed(hy - hx) : '—', mx === null ? '—' : fmt(mx), my === null ? '—' : fmt(my), mx !== null && my !== null ? signed(my - mx) : '—', x ? x.sload.ops : '—', y ? y.sload.ops : '—']; }));
lines.push('SLOADs by kind for the reverse locator and the born-after-d reads:', '');
for (const id of ['hook-remove-clear', 'hook-rebind-field-change', 'coverage-init', 'probe-tail-miss', 'probe-uncovered-revert']) for (const [name, run] of [[A, a], [B, b]]) { const o = run.ops.get(id); if (o) lines.push('- `' + id + '` ' + name + ': ' + Object.entries(o.sload.byKind).filter(([k]) => /^Word:k8|^Word:k10|^Posting:k10|^BindingKey$|^Binding$|^Store$/.test(k)).map(([k, v]) => k + ' ' + v.reads).join(', ')); }
lines.push('', '## Population and oracle', '');
table(['', A, B], [['placements', a.env.wall.populateBig.n, b.env.wall.populateBig.n], ['population wall (ms)', fmt(a.env.wall.populateBig.ms), fmt(b.env.wall.populateBig.ms)], ['population gas total', fmt(Number(a.env.wall.populateBig.totalGas)), fmt(Number(b.env.wall.populateBig.totalGas))], ['gas per placement', fmt(Number(a.env.wall.populateBig.totalGas) / a.env.wall.populateBig.n), fmt(Number(b.env.wall.populateBig.totalGas) / b.env.wall.populateBig.n)], ['oracle positions / checked / mismatches', a.env.oracle.positions + ' / ' + a.env.oracle.checked + ' / ' + a.env.oracle.mismatches.length, b.env.oracle.positions + ' / ' + b.env.oracle.checked + ' / ' + b.env.oracle.mismatches.length], ['residual 0 / model mismatches 0 (of ops)', [...a.ops.values()].filter(o => o.residual === 0).length + ' / ' + [...a.ops.values()].filter(o => o.checks.sstoreModelMismatches === 0).length + ' of ' + a.ops.size, [...b.ops.values()].filter(o => o.residual === 0).length + ' / ' + [...b.ops.values()].filter(o => o.checks.sstoreModelMismatches === 0).length + ' of ' + b.ops.size]]);
console.log(lines.join('\n'));
