#!/usr/bin/env node
// tables.md for one retained run: computed ONLY from summary.json / analysis.json.
//   node scripts/report.mjs --label n1000
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { LAB } from './lab-fixture.mjs';

const args = process.argv.slice(2);
const opt = (name, dflt) => { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : dflt; };
const LABEL = opt('--label', 'n1000');
const OUT = resolve(LAB, 'evidence/' + LABEL);
const read = p => JSON.parse(readFileSync(p, 'utf8'));
const summary = read(join(OUT, 'summary.json'));
const env = read(join(OUT, 'environment.json'));
const ops = new Map(summary.operations.map(o => [o.op, { ...o, analysis: read(join(OUT, o.op, 'analysis.json')) }]));
const fmt = n => typeof n === 'number' ? Math.round(n).toLocaleString('en-US') : String(n);
const f1 = n => (Math.round(n * 10) / 10).toLocaleString('en-US');
const lines = [];
const h = (l, t) => lines.push('', '#'.repeat(l) + ' ' + t, '');
const table = (header, rows) => { lines.push('| ' + header.join(' | ') + ' |', '| ' + header.map(() => '---').join(' | ') + ' |'); for (const r of rows) lines.push('| ' + r.join(' | ') + ' |'); lines.push(''); };
const cls = o => { const c = o.sstore.classes; return `${c.FRESH ?? 0} / ${c.COLD_REWRITE ?? 0} / ${c.WARM_REWRITE ?? 0} / ${c.NOOP ?? 0} / ${c.CLEAR ?? 0}`; };
const get = id => ops.get(id);
const hookSelf = o => o.analysis.byContract['IndexedAdmission (hook)']?.gas ?? 0;
const moduleSelf = o => o.analysis.byContract['IndexLayerModule']?.gas ?? 0;

lines.push('# Index-layer lab tables — run `' + LABEL + '` (generated)', '', 'Generated by `node scripts/report.mjs --label ' + LABEL + '` from `evidence/' + LABEL + '/**/analysis.json`. Every number is MEASURED from a retained artifact unless marked ESTIMATED. Do not edit by hand.', '');
h(2, 'Run');
table(['N (big scope)', 'sparse scope', 'commit', 'dirty', 'anvil', 'solc', 'elapsed', 'populate wall (ms)', 'rehosts'],
  [[env.n, env.sparse, (env.git.commit ?? '').slice(0, 12), String(env.git.dirty), env.versions.anvil.replace('anvil Version: ', ''), env.versions.solc.version, Math.round(env.elapsedMs / 1000) + ' s', fmt(env.wall.populateBig.ms) + ' for ' + env.wall.populateBig.n + ' placements (' + fmt(env.wall.populateBig.ms / env.wall.populateBig.n) + ' ms each)', env.rehosts.map(r => r.why + ' (state ' + f1(r.stateBytes / 1048576) + ' MiB, previous node RSS ' + fmt(r.rssOfPreviousNodeBytes / 1048576) + ' MiB, ' + f1(r.ms / 1000) + ' s)').join('; ')]]);
lines.push('Code sizes (runtime bytes): U4 core ' + fmt(env.codeSizes.core4) + ', module ' + fmt(env.codeSizes.module) + ', hook library ' + fmt(env.codeSizes.hook) + '. Final anvil RSS ' + fmt(env.finalAnvilRssBytes / 1048576) + ' MiB.', '');

h(2, 'Every retained transaction');
table(['op', 'status', 'receipt', 'intrinsic', 'exec gross', 'SSTORE ops (FRESH / COLD / WARM / NOOP / CLEAR)', 'SSTORE gas', 'SLOAD ops', 'SLOAD gas', 'hook frame self gas', 'module frame self gas', 'residual', 'model mismatches', 'unattributed reads'],
  [...ops.values()].map(o => [o.op, o.status, fmt(o.receiptGasUsed), fmt(o.intrinsic), fmt(o.gross), cls(o), fmt(o.categories.SSTORE), fmt(o.sload.ops), fmt(o.sload.gas), fmt(hookSelf(o)), fmt(moduleSelf(o)), o.residual, o.checks.sstoreModelMismatches, o.checks.unattributedReads]));

h(2, 'Hook cost: U3 → U4 unattached → attached');
const trio = (a, b, c) => { const A = get(a), Bq = get(b), C = get(c); return [a + ' / ' + b + ' / ' + c, fmt(A.receiptGasUsed), fmt(Bq.receiptGasUsed), fmt(C.receiptGasUsed), fmt(Bq.receiptGasUsed - A.receiptGasUsed), fmt(C.receiptGasUsed - Bq.receiptGasUsed), cls(A) + ' → ' + cls(Bq) + ' → ' + cls(C), fmt(hookSelf(Bq)), fmt(hookSelf(C))]; };
table(['ops (U3 / U4 unattached / attached)', 'U3 receipt', 'U4 unattached receipt', 'attached receipt', 'U4 wrapper delta', 'attach delta', 'FRESH/COLD/WARM/NOOP/CLEAR per op', 'hook self gas (unattached)', 'hook self gas (attached)'], [
  trio('u3-placement-1', 'u4-placement-1', 'hook-placement-fresh-word'),
  trio('u3-placement-2', 'u4-placement-2', 'hook-placement-warm-word'),
  trio('u3-placement-0', 'u4-placement-0', 'hook-placement-second-bucket'),
  trio('u3-remove', 'u4-remove', 'hook-remove-clear'),
  trio('u3-restore', 'u4-restore', 'hook-restore-set'),
]);
lines.push('Receipt deltas carry the posting-word boundary noise of the baseline (±17,100 per FRESH word crossing, see gas-baseline §4): read the FRESH counts next to the gas. The hook frame self gas is the gas executed by the IndexedAdmission code itself (pre-read, nested-call encoding, post-hook, its own SLOAD/SSTOREs), independent of that noise.', '');
const hookKinds = o => Object.entries(o.sload.byKind).filter(([k]) => /^Index|^Word:k8|^Word:k10|^Posting:k10|^Binding$|^Record:/.test(k)).map(([k, v]) => k + ' ' + v.reads + 'r').join(', ');
table(['op', 'hook self gas', 'SLOADs by kind touched by the hook (reads)', 'SSTOREs on IndexWord (class)', 'note'],
  ['u4-placement-1', 'hook-placement-fresh-word', 'hook-placement-warm-word', 'hook-placement-second-bucket', 'hook-remove-clear', 'hook-restore-set', 'hook-rebind-field-change', 'hook-rebind-uncovered'].map(id => { const o = get(id); const w = o.sstoreByKind.IndexWord; return [id, fmt(hookSelf(o)), hookKinds(o), w ? JSON.stringify(w.classes) + ' ' + fmt(w.gas) : '—', o.note]; }));

h(2, 'Backfill: chunks and the per-entry walk');
const chunkIds = [...ops.keys()].filter(k => /^backfill-(\d+)$/.test(k)).sort((a, b) => Number(a.split('-')[1]) - Number(b.split('-')[1]));
table(['chunk', 'entries', 'receipt', 'receipt per entry', 'exec gross', 'SLOAD ops', 'SLOAD ops per entry', 'SSTORE ops (FRESH / COLD / WARM / NOOP / CLEAR)', 'IndexWord writes', 'residual'],
  chunkIds.map(id => { const o = get(id); const n = Number(id.split('-')[1]); const w = o.sstoreByKind.IndexWord; return [id, n, fmt(o.receiptGasUsed), fmt(o.receiptGasUsed / n), fmt(o.gross), fmt(o.sload.ops), f1(o.sload.ops / n), cls(o), w ? JSON.stringify(w.classes) : '—', o.residual]; }));
function perEntry(aId, bId) {
  const a = get(aId), b = get(bId); const na = Number(aId.split('-')[1]), nb = Number(bId.split('-')[1]); const dn = nb - na;
  const kinds = new Set([...Object.keys(a.sload.byKind), ...Object.keys(b.sload.byKind)]);
  const rows = [...kinds].map(k => { const ra = a.sload.byKind[k] ?? { reads: 0, gas: 0 }, rb = b.sload.byKind[k] ?? { reads: 0, gas: 0 }; return { kind: k, reads: (rb.reads - ra.reads) / dn, gas: (rb.gas - ra.gas) / dn }; }).filter(r => Math.abs(r.reads) > 1e-9).sort((x, y) => y.gas - x.gas);
  const totalReads = rows.reduce((s, r) => s + r.reads, 0), totalGas = rows.reduce((s, r) => s + r.gas, 0);
  const cat = Object.fromEntries(Object.keys(b.categories).map(c => [c, (b.categories[c] - a.categories[c]) / dn]));
  return { rows, totalReads, totalGas, cat, gross: (b.gross - a.gross) / dn, receipt: (b.receiptGasUsed - a.receiptGasUsed) / dn, fixed: a.receiptGasUsed - na * (b.receiptGasUsed - a.receiptGasUsed) / dn, dn, aId, bId };
}
const pairs = []; for (let i = 1; i < chunkIds.length; i++) pairs.push(perEntry(chunkIds[i - 1], chunkIds[i]));
for (const p of pairs) {
  h(3, 'Per-entry marginal from ' + p.aId + ' → ' + p.bId + ' (Δ' + p.dn + ' entries; MEASURED deltas divided by the entry delta)');
  lines.push('Receipt per entry **' + fmt(p.receipt) + '**, execution gross per entry ' + fmt(p.gross) + ', implied fixed cost per call ' + fmt(p.fixed) + '. Categories per entry: ' + Object.entries(p.cat).filter(([, v]) => Math.abs(v) >= 1).map(([k, v]) => k + ' ' + fmt(v)).join(', ') + '.', '');
  table(['StateStore kind', 'SLOADs per entry', 'SLOAD gas per entry', 'share of SLOAD gas'], [...p.rows.map(r => [r.kind, f1(r.reads), fmt(r.gas), (100 * r.gas / p.totalGas).toFixed(1) + '%']), ['**total**', f1(p.totalReads), fmt(p.totalGas), '100%']]);
  const k10skips = p.rows.filter(r => /^Admission$|^Envelope$|^Record:BindingSet\/1$|^Record:BindingTombstone\/1$/.test(r.kind));
  const skipReads = k10skips.reduce((s, r) => s + r.reads, 0), skipGas = k10skips.reduce((s, r) => s + r.gas, 0);
  lines.push('**K10 saving (ESTIMATED, not claimed):** under K10 the kind-10 word carries the binding-key ordinal, so admission row → envelope bytes → BindingSet/Tombstone record body → binding key are replaced by one `bindingKeys[ordinal]` read (2,100 cold). The rows this walk reads for that leg: ' + k10skips.map(r => r.kind + ' ' + f1(r.reads)).join(', ') + ' = ' + f1(skipReads) + ' SLOADs, ' + fmt(skipGas) + ' gas per entry. Estimated saving ≈ ' + fmt(skipGas - 2100) + ' gas per entry in SLOAD alone (' + (100 * (skipGas - 2100) / p.receipt).toFixed(0) + '% of the per-entry receipt), plus the keccak/memory plumbing of decoding those rows, which is not separated here. The remaining walk (kind-10 word, binding row, target record type + body, bit word) stays.', '');
}

h(2, 'Largest chunk under 16,777,216');
table(['maxEntries tried', 'eth_estimateGas', 'status', 'gasUsed'], env.maxChunk.attempts.map(a => [a.maxEntries, typeof a.estimateGas === 'number' ? fmt(a.estimateGas) : String(a.estimateGas), a.status, fmt(a.gasUsed)]));
lines.push('Per-entry estimate used for the first attempt: ' + fmt(env.maxChunk.perEntryEstimate) + ' (fixed ' + fmt(env.maxChunk.fixedEstimate) + '), from the last two standard chunks. ' + (env.wall.finishBig.skipped ? env.wall.finishBig.skipped : 'Finishing the scope afterwards took ' + env.wall.finishBig.extraCalls + ' more 256-entry call(s), ' + fmt(env.wall.finishBig.ms) + ' ms.'), '');

h(2, 'Coverage-slot init, reads, sparse arm, declare, upgrade');
table(['op', 'receipt', 'exec gross', 'SLOAD ops / gas', 'SSTORE ops (FRESH / COLD / WARM / NOOP / CLEAR)', 'module self gas', 'note'],
  ['declare', 'coverage-init', 'coverage-init-2', 'probe-hit', 'probe-miss-covered', 'probe-tail-miss', 'probe-uncovered-revert', 'probe-tolerated', 'page-hot-256', 'page-hot-512', 'page-sparse', 'backfill-sparse-' + env.sparse, 'u4-upgrade'].filter(id => ops.has(id)).map(id => { const o = get(id); return [id, fmt(o.receiptGasUsed), fmt(o.gross), o.sload.ops + ' / ' + fmt(o.sload.gas), cls(o), fmt(moduleSelf(o)), o.note]; }));
{
  const sp = get('backfill-sparse-' + env.sparse);
  if (sp) lines.push('Sparse arm per entry (receipt / ' + env.sparse + ', includes its slot init): **' + fmt(sp.receiptGasUsed / env.sparse) + '**; IndexWord writes ' + JSON.stringify(sp.sstoreByKind.IndexWord?.classes ?? {}) + ' (' + fmt(sp.sstoreByKind.IndexWord?.gas ?? 0) + ' gas, ' + fmt((sp.sstoreByKind.IndexWord?.gas ?? 0) / env.sparse) + ' per entry).', '');
  const p256 = get('page-hot-256'); if (p256) lines.push('page-hot-256 SLOADs by kind: ' + Object.entries(p256.sload.byKind).map(([k, v]) => k + ' ' + v.reads).join(', ') + '.', '');
  const ph = get('probe-hit'); if (ph) lines.push('probe-hit SLOADs by kind: ' + Object.entries(ph.sload.byKind).map(([k, v]) => k + ' ' + v.reads).join(', ') + '; probe-miss-covered: ' + Object.entries(get('probe-miss-covered').sload.byKind).map(([k, v]) => k + ' ' + v.reads).join(', ') + '.', '');
}
h(2, 'Differential oracle');
lines.push('Positions walked ' + env.oracle.positions + (env.oracle.sample ? ' (sample rule: ' + env.oracle.sample.rule + '; through ' + env.oracle.sample.through + ', liveFrom ' + env.oracle.sample.liveFrom + ', count ' + env.oracle.sample.count + ')' : '') + ', probes checked ' + env.oracle.checked + ', mismatches ' + env.oracle.mismatches.length + ' (' + fmt(env.oracle.ms) + ' ms).', '');
h(2, 'Cross-checks');
const bad = [...ops.values()].filter(o => o.residual !== 0 || o.checks.sstoreModelMismatches !== 0 || (o.status === '0x1' && o.checks.prestateDiffMismatches !== 0));
lines.push('Residual (intrinsic + gross − refund − receipt) is 0 for ' + [...ops.values()].filter(o => o.residual === 0).length + ' of ' + ops.size + ' transactions; SSTORE EIP-2200/2929 model mismatches 0 for ' + [...ops.values()].filter(o => o.checks.sstoreModelMismatches === 0).length + '; prestateTracer diff agrees for ' + [...ops.values()].filter(o => o.status !== '0x1' || o.checks.prestateDiffMismatches === 0).length + '.' + (bad.length ? ' **Exceptions:** ' + bad.map(o => o.op + ' (residual ' + o.residual + ', model ' + o.checks.sstoreModelMismatches + ', prestate ' + o.checks.prestateDiffMismatches + ')').join('; ') : ''), '');
writeFileSync(join(OUT, 'tables.md'), lines.join('\n') + '\n');
console.log('wrote', join(OUT, 'tables.md'));
