// Run-local assembly from independently authored inputs and root-reviewed build; no RPC.
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
const run='/tmp/efs-b-parity-paid-20260913.KJ23qU';
const repo='/Users/james/Code/EFS/planning-warroom-b-run';
const lab=`${repo}/Reviews/2026-09-12-efs-path-decision/lab-b`;
const source='c5561e2b27c48ca2938695cce7784f1e78564116';
const input='/tmp/efs-b-parity-inputs-20260913.AHqH23/b-parity-inputs.json';
const oracle='/Users/james/Code/EFS/planning-warroom-oracle/Reviews/2026-09-12-efs-path-decision/lab-oracle';
const buildRoot='/tmp/efs-b-parity-build-20260913.lcAzU1';
const sha=b=>createHash('sha256').update(b).digest('hex');
const fileHash=p=>sha(readFileSync(p));
const git=args=>execFileSync('git',args,{cwd:repo,encoding:'utf8'});
assert.match(process.argv[2]??'',/^[0-9a-f]{64}$/,'independently reviewed input SHA required');
assert.equal(fileHash(input),process.argv[2]);
assert.equal(git(['rev-parse','HEAD']).trim(),source);
assert.equal(git(['diff','HEAD','--binary']),'');
assert.equal(git(['ls-files','--others','--exclude-standard','--','Reviews/2026-09-12-efs-path-decision/lab-b']),'');
const p=JSON.parse(readFileSync(input));
assert.equal(p.sourceCommit,source);
const b=JSON.parse(readFileSync(`${buildRoot}/green2.json`));
assert.equal(b.sourceUnchangedDuringRun,true);assert.equal(b.diffUnchangedDuringRun,true);
assert.equal(b.stages.length,4);for(const s of b.stages)assert.equal(s.exitCode,0);
for(const [rel,hash]of Object.entries(b.sourceHashes))assert.equal(fileHash(`${lab}/${rel}`),hash,rel);
for(const [rel,hash]of Object.entries(b.artifactHashes))assert.equal(fileHash(`${buildRoot}/green-out/${rel}`),hash,rel);
for(const pin of Object.values(p.sourcePins))assert.equal(fileHash(pin.path),pin.sha256);
for(const pin of Object.values(p.artifactPins))assert.equal(fileHash(pin.path),pin.sha256);
for(const pin of Object.values(p.helpers))assert.equal(fileHash(pin.path),pin.sha256);
assert.equal(fileHash(p.neutralPin.path),p.neutralPin.sha256);
const sourceHashes={};
for(const dir of ['src','test','script'])for(const name of readdirSync(`${lab}/${dir}`).sort())sourceHashes[`${dir}/${name}`]=fileHash(`${lab}/${dir}/${name}`);
const targets={},artifacts={};
for(const [name,t]of Object.entries(p.runtime.targets)){
  targets[name]={address:t.address,runtime:t.expectedRuntime};
  const pin=p.artifactPins[`${t.sourceName}:${t.contractName}`];
  assert.equal(pin.compiler.version,'0.8.30+commit.73712a01');
  assert.equal(pin.settings.viaIR,true);assert.equal(pin.settings.optimizer.enabled,true);assert.equal(pin.settings.optimizer.runs,200);assert.equal(pin.settings.evmVersion,'cancun');
  assert(t.runtimeBytes<=24576 && t.initcodeBytes<=49152,`normal limits:${name}`);
  artifacts[name]={artifactSha256:pin.sha256,initcodeHash:t.initcodeHash,runtimeCodehash:t.runtimeCodehash,runtimeBytes:t.runtimeBytes};
}
assert.equal(Object.keys(targets).length,17);
const arm={schema:'efs-paid-arm/1',runId:'b-parity-paid-20260913-KJ23qU',chainId:31337,expectationsSha256:p.neutralPin.sha256,retentionDir:`${run}/independent-observations`,source:{commit:source,dirtyDiffSha256:sha(''),sourceHashes},build:{solc:'0.8.30+commit.73712a01',viaIR:true,optimizerRuns:200,evm:'cancun',artifacts},plannedCells:['joined/paid-slice'],firstCell:'joined/paid-slice',inputs:p.inputs,targets,initial:p.rawChecks.initial,checkpoint:p.rawChecks.checkpoint,checks:p.rawChecks.checks,localDependencies:[],preparation:{inputPath:input,inputSha256:process.argv[2],greenBuildSha256:fileHash(`${buildRoot}/green2.json`),independentlyExpectedPaidRows:p.paidRows.length,evidenceCeiling:'RPC_OBSERVED',unverified:p.rawChecks.unverified}};
const controller=`${oracle}/paid-controller.mjs`;
const pins={runId:arm.runId,source,armInput:`${run}/arm-b.json`,armSha256:null,controller,controllerSha256:fileHash(controller),neutral:p.neutralPin.path,neutralSha256:p.neutralPin.sha256,independentInputs:input,independentInputSha256:process.argv[2],artifacts:`${buildRoot}/green-out`};
writeFileSync(pins.armInput,`${JSON.stringify(arm,null,2)}\n`,{flag:'wx'});pins.armSha256=fileHash(pins.armInput);
writeFileSync(`${run}/pins.json`,`${JSON.stringify(pins,null,2)}\n`,{flag:'wx'});
console.log(JSON.stringify({runId:pins.runId,source,inputSha256:process.argv[2],armSha256:pins.armSha256,controllerSha256:pins.controllerSha256,targets:17,checksBefore:arm.checks.beforeFixture.length,checksAfter:arm.checks.afterB1.length}));
