import test from 'node:test';
import assert from 'node:assert/strict';
import {createEnvironment} from '../script/compact-environment.mjs';
import {createFilesCompactSdk} from './compact-files-sdk.mjs';
import {describe,encryptContent} from './compact-content.mjs';
import {startRawCarrier} from '../script/raw-carrier-fixture.mjs';
import {createRawTransport,storeRawBytes} from './compact-carrier-host.mjs';
import {samplePng} from '../script/carrier-fixtures.mjs';
import {startBrowser} from '../script/compact-browser.mjs';
test('cold guarded Files preserve binary, descriptors, revision lineage and scoped Concept labels',{timeout:120000},async t=>{
  const env=await createEnvironment({protocol:'compact-guarded-v2',deployment:'proxy',filesProfile:'typed-directory-v1',contentProfile:'raw-sha256-aesgcm-v1'});t.after(()=>env.close());
  assert.equal(env.manifest.contentProfile,'raw-sha256-aesgcm-v1');
  const {ethers:e,manifest,wallets,rpc}=env,authors=Object.values(manifest.authors),binary=Uint8Array.of(0,255,128,65);
  const fixture=await startRawCarrier([samplePng()]);t.after(()=>fixture.close());
  const browser=await startBrowser(env,{seed:false,directory:true,carrierFixture:fixture});t.after(()=>browser.close());
  assert.match(await (await fetch(browser.url)).text(),/carrier-entry/);
  for(const module of ['carrier-entry.mjs','compact-content.mjs','compact-carrier-host.mjs','compact-files-sdk.mjs'])assert.equal((await fetch(new URL(module,browser.url))).status,200);
  assert.equal((await fetch(new URL('carrier.integration.test.mjs',browser.url))).status,404);
  const sdk=createFilesCompactSdk({ethers:e,manifest,rpc,journal:await env.createJournal('carriers')});
  const run=async(operation,args)=>{
    const p=await sdk.prepare({operation,author:wallets.alice.address,authors,...args});
    const signed=await sdk.authorize(p,d=>wallets.alice.signingKey.sign(d).serialized);
    await sdk.submit(signed,tx=>env.send(`${operation}/${args.name??args.scope??''}`,tx,'alice'));
    assert.equal((await sdk.reconcile(p.id)).status,'EFFECTS_VERIFIED');return p;
  };
  const inline=await run('create',{name:'binary.bin',salt:e.id('binary'),content:{bytes:binary}});
  const reused=await run('create',{name:'reused.bin',salt:e.id('reused'),content:{bytes:binary}});
  assert(reused.bodies.filter(b=>b!=='0x').length<inline.bodies.filter(b=>b!=='0x').length,'retained content should be reused');
  const empty=await run('create',{name:'empty.bin',salt:e.id('empty'),content:{bytes:new Uint8Array()}});
  const externalDescriptor=await describe(binary,{carrier:1});
  const external=await run('create',{name:'external.bin',salt:e.id('external'),content:{descriptor:externalDescriptor}});
  await run('create',{name:'external2.bin',salt:e.id('external2'),content:{descriptor:externalDescriptor}});
  const key=crypto.getRandomValues(new Uint8Array(32)),sealed=await encryptContent(binary,key);
  const encrypted=await run('create',{name:'encrypted.bin',salt:e.id('encrypted'),content:sealed});
  const png=samplePng(),image=await run('create',{name:'real.png',salt:e.id('real-png'),content:{descriptor:await describe(png,{carrier:1,media:2})}});
  const large=new Uint8Array(9000);large[8193]=255;await storeRawBytes(large,{origin:fixture.origin});
  const uploaded=await run('create',{name:'large.bin',salt:e.id('large'),content:{descriptor:await describe(large,{carrier:1})}});
  const largest=Uint8Array.from({length:8160},(_,i)=>i%251+1);largest[8159]=255;
  const maxInline=await run('create',{name:'max-inline.bin',salt:e.id('max-inline'),content:{bytes:largest}});
  // Reuse the already retained Bytes on a later transaction, but publish a new
  // descriptor media declaration. This exercises the cold bounded header join.
  const maxReused=await run('create',{name:'max-reused.bin',salt:e.id('max-reused'),content:{bytes:largest,media:2}});
  const concept=await run('addTag',{file:inline.file,scope:'revision',conceptLabel:'vacation'});
  await run('addTag',{file:inline.file,scope:'file',concept:concept.concept});
  const directory=await run('createDirectory',{name:'photos',salt:e.id('photos')});
  await run('addTag',{file:directory.file,scope:'directory',concept:concept.concept});
  await assert.rejects(sdk.prepare({operation:'addTag',file:directory.file,scope:'revision',concept:concept.concept,author:wallets.alice.address,authors}),/FILE_SUBJECT|TAG_SCOPE/);
  const cold=createFilesCompactSdk({ethers:e,manifest,rpc});
  const open=async(file,options={})=>cold.readContent({file,authors,context:await cold.pin(),...options});
  assert.deepEqual((await open(inline.file)).bytes,binary);assert.deepEqual((await open(empty.file)).bytes,new Uint8Array());
  assert.equal((await open(external.file)).state,'UNAVAILABLE');
  assert.deepEqual((await open(external.file,{loadCarrier:async()=>binary})).bytes,binary);
  assert.equal((await open(encrypted.file)).state,'OPAQUE');assert.deepEqual((await open(encrypted.file,{key})).bytes,binary);
  assert.deepEqual((await open(image.file,{loadCarrier:createRawTransport({origin:fixture.origin})})).bytes,png);
  assert.deepEqual((await open(uploaded.file,{loadCarrier:createRawTransport({origin:fixture.origin})})).bytes,large);
  assert.deepEqual((await open(maxInline.file)).bytes,largest);assert.deepEqual((await open(maxReused.file)).bytes,largest);
  assert.equal((await open(encrypted.file,{key:new Uint8Array(32)})).reason,'AUTHENTICATION_FAILED');
  assert.equal((await cold.readConcept({concept:concept.concept,context:await cold.pin()})).value.label,'vacation');
  const folderTag=await cold.readTag({subject:directory.file,target:directory.file,concept:concept.concept,authors,context:await cold.pin()});
  assert.equal(folderTag.value.present,true);assert.equal(folderTag.value.subject,directory.file);
  const old=inline.newRevision;await run('edit',{file:inline.file,document:'edited'});
  assert.deepEqual((await open(inline.file,{record:old})).bytes,binary);
  const tags=await cold.readFile({file:inline.file,authors,concept:concept.concept,context:await cold.pin()});
  assert.equal(tags.value.fileTag.present,true);assert.equal(tags.value.revisionTag.present,false);
  await run('restoreContents',{file:inline.file,record:old});assert.deepEqual((await open(inline.file)).bytes,binary);
  assert.equal((await cold.readConcept({concept:e.id('missing-concept'),context:await cold.pin()})).knowledge,'UNKNOWN');
  const iface=new e.Interface(manifest.contracts.ledger.abi),missingCall=iface.encodeFunctionData('record',[concept.concept]);
  const missing=createFilesCompactSdk({ethers:e,manifest,rpc:(method,params)=>{if(method==='eth_call'&&params[0].data===missingCall)throw Error('retention unavailable');return rpc(method,params);}});
  assert.equal((await missing.readConcept({concept:concept.concept,context:await missing.pin()})).knowledge,'UNKNOWN');
  const other=sdk.conceptId({namespace:e.id('other-namespace'),label:'vacation'});assert.notEqual(other,concept.concept);
  await env.writeReport('carriers',{transactions:env.transactions,metrics:env.metrics,bytes:{binary:Array.from(binary),download:Array.from((await open(inline.file)).bytes)}});
});
