import test from 'node:test';
import assert from 'node:assert/strict';
import {startWorkbench} from '../script/workbench-browser.mjs';
import {createFilesCompactSdk} from './compact-files-sdk.mjs';
import {hydrateExactStances} from './compact-stance.mjs';
import {filterRows} from './files-view.mjs';

test('exact stances use the normal journal, ordered Lens and selected HEAD guards',{timeout:240000},async t=>{
  const w=await startWorkbench({serve:false,uiPort:60629});t.after(()=>w.close());
  const {env,seed}=w,{ethers:e}=env,authors=Object.values(env.manifest.authors);
  const journal=await env.createJournal('exact-stance');
  const sdk=createFilesCompactSdk({ethers:e,manifest:env.manifest,rpc:env.rpc,journal});
  const prepare=(operation,extra={},who='alice')=>sdk.prepare({operation,author:env.wallets[who].address,authors,file:seed.meeting.file,scope:'file',...extra});
  const send=async(plan,who='alice')=>{
    const signed=await sdk.authorize(plan,d=>env.wallets[who].signingKey.sign(d).serialized);
    await sdk.submit(signed,tx=>env.send('exact/'+plan.operation,tx,who));
    const cold=createFilesCompactSdk({ethers:e,manifest:env.manifest,rpc:env.rpc,journal});
    assert.equal((await cold.reconcile(plan.id)).status,'EFFECTS_VERIFIED');
  };
  const first=await prepare('assertStance',{conceptNamespace:env.manifest.folder,conceptLabel:'exact'});
  assert.deepEqual(first.actions.map(a=>a.kind),[1,3]);await send(first);
  const concept=first.concept;
  const point=async(order=authors,extra={})=>sdk.readStance({subject:seed.meeting.file,scope:'file',concept,authors:order,context:await sdk.pin(),...extra});
  await send(await prepare('denyStance',{concept},'bob'),'bob');
  const asserted=await point();assert.equal(asserted.value.assessment,'PRESENT',JSON.stringify(asserted.value));
  assert.equal((await point([...authors].reverse())).value.assessment,'NOT_PRESENT');
  const silent=await prepare('retractToSilent',{concept});assert.equal(silent.actions[0].expectedRevision,1);await send(silent);
  const after=await point();assert.equal(after.value.assessment,'NOT_PRESENT');assert.equal(after.value.observations[0].kind,'SILENT');assert.equal(after.value.stance,'DENY');
  await send(await prepare('retractToSilent',{concept},'bob'),'bob');
  assert.equal((await point()).value.assessment,'NOT_PRESENT');assert.equal((await point()).value.stance,null);
  await send(await prepare('assertStance',{concept,scope:'directory',file:seed.docs.file}));
  assert.equal((await point(authors,{subject:seed.docs.file,scope:'directory'})).value.assessment,'PRESENT');
  assert.equal((await point()).value.assessment,'NOT_PRESENT','Directory stance does not inherit');
  const stale=await prepare('assertStance',{concept,scope:'selectedRevision'});
  await w.run('edit',{file:seed.meeting.file,document:'changed HEAD'});
  let prompted=false;await assert.rejects(sdk.authorize(stale,()=>{prompted=true;}),/DRIFT/);assert.equal(prompted,false);
  const pending=await prepare('assertStance',{concept,scope:'selectedRevision'});
  const signed=await sdk.authorize(pending,d=>env.wallets.alice.signingKey.sign(d).serialized);
  await w.run('edit',{file:seed.meeting.file,document:'changed again'});
  await assert.rejects(sdk.submit(signed,()=>assert.fail('must not send stale stance')),/DRIFT/);
  await send(await prepare('assertStance',{concept,scope:'selectedRevision'}));
  assert.equal((await point(authors,{scope:'selectedRevision'})).value.assessment,'PRESENT');
  assert.equal((await point(authors,{concept:env.tags.tokens[0]})).value.assessment,'UNKNOWN');
  assert.equal((await point(authors,{subject:env.tags.revision1,scope:'file'})).value.assessment,'UNKNOWN');
  const old=await sdk.readTag({subject:seed.meeting.file,target:seed.meeting.file,concept:sdk.conceptId({namespace:env.manifest.folder,label:'efs'}),authors,context:await sdk.pin()});
  assert.equal(old.value.assessment,'PRESENT');
  assert.equal((await point(authors,{concept:sdk.conceptId({namespace:env.manifest.folder,label:'efs'})})).value.assessment,'NOT_PRESENT');
  await send(await prepare('assertStance',{concept},'bob'),'bob');
  await env.transact('ledger','unbind',[env.tags.purpose,seed.meeting.file,concept,2],'exact/tombstone','alice');
  const tombstone=await point();assert.equal(tombstone.value.assessment,'PRESENT');assert.equal(tombstone.value.observations[0].kind,'TOMBSTONE');
  const abi=new e.Interface(env.contracts.ledger.abi);
  const position=(await env.call('lens','positionKey',[env.tags.purpose,seed.meeting.file,concept]))[0];
  const key=e.keccak256(e.AbiCoder.defaultAbiCoder().encode(['bytes32','bytes32','bytes32'],[e.id('efs2/binding/1'),env.tags.principals.alice,position]));
  const failedData=abi.encodeFunctionData('head',[key]);
  const unavailable=createFilesCompactSdk({ethers:e,manifest:env.manifest,rpc:(method,params)=>{
    if(method==='eth_call'&&params[0].data===failedData)throw Error('injected unavailable earlier author');return env.rpc(method,params);
  }});
  const unknown=await unavailable.readStance({subject:seed.meeting.file,scope:'file',concept,authors,context:await unavailable.pin()});
  assert.equal(unknown.value.assessment,'UNKNOWN','unavailable earlier author cannot fall through to Bob ASSERT');
  assert.equal(unknown.value.observations[1].kind,'ASSERT');
  const context=await sdk.pin(),page=await sdk.listFolderPage({folder:seed.docs.file,authors,concept:e.ZeroHash,tagScope:'none',context,budget:32});
  const row=page.pageRows.find(r=>r.file===seed.meeting.file);
  const hydrated=await hydrateExactStances({sdk,row,concept,authors,context});
  assert.equal(hydrated.point.value.fileTag.assessment,'PRESENT');assert.equal(filterRows([hydrated],{tag:true,scope:'file'}).rows.length,1);
  const unknownRow={...hydrated,point:{...hydrated.point,value:{...hydrated.point.value,fileTag:unknown.value}}};
  assert.equal(filterRows([unknownRow],{tag:true,scope:'file'}).uncertain,1);
  const unsupported=structuredClone(env.manifest);
  unsupported.contracts.index.abi=unsupported.contracts.index.abi.filter(x=>!['tagProfileHash','stanceValidator','stanceValidatorHash'].includes(x.name));
  const legacy=createFilesCompactSdk({ethers:e,manifest:unsupported,rpc:env.rpc});
  assert.equal(legacy.exactStances,false);
  assert.equal((await legacy.readStance({subject:seed.meeting.file,scope:'file',concept,authors,context:await legacy.pin()})).value.assessment,'UNKNOWN');
  await assert.rejects(legacy.prepare({operation:'assertStance',author:authors[0],authors,file:seed.meeting.file,scope:'file',concept}),/STANCE_PROFILE_UNSUPPORTED/);
  assert.equal((await legacy.readTag({subject:seed.meeting.file,target:seed.meeting.file,concept:sdk.conceptId({namespace:env.manifest.folder,label:'efs'}),authors,context:await legacy.pin()})).value.assessment,'PRESENT');
  const wrongValidator=createFilesCompactSdk({ethers:e,manifest:env.manifest,rpc:(method,params)=>{
    if(method==='eth_getCode'&&params[0].toLowerCase()===env.contracts.stanceValidator.address.toLowerCase())return Promise.resolve('0x00');return env.rpc(method,params);
  }});
  assert.equal((await wrongValidator.readStance({subject:seed.meeting.file,scope:'file',concept,authors,context:await wrongValidator.pin()})).value.assessment,'UNKNOWN');
  await assert.rejects(wrongValidator.prepare({operation:'assertStance',author:authors[0],authors,file:seed.meeting.file,scope:'file',concept}),/VALIDATOR_CODE/);
  const update=await sdk.prepare({operation:'edit',author:authors[0],authors,file:seed.meeting.file,document:'approved update',
    replacementPlacement:{folder:seed.docs.file,name:'meeting.txt',target:seed.meeting.file}});
  const updateSigned=await sdk.authorize(update,d=>env.wallets.alice.signingKey.sign(d).serialized);
  await w.run('linkPlacement',{folder:seed.docs.file,name:'meeting.txt',file:seed.image.file,replace:true});
  await assert.rejects(sdk.submit(updateSigned,()=>assert.fail('must not send after inspected destination changes')),/DRIFT/);
  await env.writeReport('exact-stance',{transactions:env.transactions.filter(x=>x.label.startsWith('exact/'))});
  console.log('EXACT_STANCE_EVIDENCE',env.dir);
});
