import test from 'node:test';
import assert from 'node:assert/strict';
import {createEnvironment} from '../script/compact-environment.mjs';
import {createFilesCompactSdk} from './compact-files-sdk.mjs';
const profile={protocol:'compact-guarded-v2',filesProfile:'typed-directory-v1',contentProfile:'raw-sha256-aesgcm-v2'};
test('joined pages qualify headers and own exact context Lens query continuations',{timeout:120000},async t=>{
  const env=await createEnvironment(profile);t.after(()=>env.close());
  const {ethers:e,manifest,rpc,wallets}=env,authors=Object.values(manifest.authors);
  const sdk=createFilesCompactSdk({ethers:e,manifest,rpc,journal:await env.createJournal('joined')});
  const run=async(operation,args)=>{
    const p=await sdk.prepare({operation,author:wallets.alice.address,authors,...args});
    const signed=await sdk.authorize(p,d=>wallets.alice.signingKey.sign(d).serialized);
    await sdk.submit(signed,tx=>env.send(operation,tx,'alice'));return p;
  };
  const file=await run('create',{name:'a.txt',salt:e.id('a'),document:'x'.repeat(41)});
  const directory=await run('createDirectory',{name:'b-dir',salt:e.id('b')});
  const concept=await run('addTag',{file:file.file,scope:'revision',conceptLabel:'approved'});
  await run('addTag',{file:directory.file,scope:'directory',concept:concept.concept});
  assert.equal(typeof sdk.listFolderPage,'function','bounded joined page API is present');
  const context=await sdk.pin(),args={context,authors,budget:1,concept:concept.concept,tagScope:'either'};
  const searched=await sdk.listFolderPage({...args,budget:16,search:'A.TXT'});
  assert.equal(searched.pageRows.length,1);assert.equal(searched.pageRows[0].name.value,'a.txt','SDK normalizes search, never changes the accepted lowercase Name grammar');
  const first=await sdk.listFolderPage(args);
  assert.equal(first.queryCoverage,'PARTIAL');assert.equal(first.scanned,'1');assert.equal(first.pageRows.length,1);
  assert.equal(first.pageRows[0].name.value,'a.txt');assert.equal(first.pageRows[0].point.value.revision.document,undefined);
  assert.equal(first.pageRows[0].point.value.revision.assurance,'HEADER_VERIFIED_BODY_NOT_FETCHED');
  assert.equal(first.pageRows[0].point.value.revisionTag.present,true);
  const warmStart=env.metrics.calls;await sdk.listFolderPage(args);
  assert(env.metrics.calls-warmStart<=2,'warm page does not reclassify every author or repeat joins');
  const point=await sdk.readFile({file:file.file,authors,context,concept:concept.concept});
  assert.equal(first.pageRows[0].point.value.revision.recordId,point.value.revision.recordId);
  const next=await sdk.listFolderPage({...args,continuation:first.continuation});
  assert.equal(next.segmentCompleteFromOrigin,false);assert.equal(next.completeFromOwnedOrigin,true);
  assert.equal(next.queryCoverage,'COMPLETE');assert.equal(next.pageRows.length,1,'only new rows, not accumulated old rows');
  assert.equal(next.pageRows[0].file,directory.file);assert.equal(next.pageRows[0].kind,'directory');
  assert.equal(next.pageRows[0].point.value.revision,null);assert.equal(next.pageRows[0].point.value.revisionTag.applicable,false);
  assert.equal(next.pageRows[0].point.value.selection,null,'Directory has no synthetic File HEAD');
  assert.equal(next.pageRows[0].point.value.fileTag.subject,directory.file);assert.equal(next.pageRows[0].point.value.fileTag.present,true);
  const onlyRevision=await sdk.listFolderPage({...args,tagScope:'revision'});
  const emptySuffix=await sdk.listFolderPage({...args,tagScope:'revision',continuation:onlyRevision.continuation});
  assert.equal(emptySuffix.pageRows.length,0);assert.equal(emptySuffix.queryCoverage,'COMPLETE');
  assert.equal(emptySuffix.queryKnowledge,'PRESENT','empty terminal segment must not erase earlier retained matches');
  assert.equal(emptySuffix.retainedSoFar,'1');assert.equal(emptySuffix.queryAbsent,false);
  assert.equal(emptySuffix.kind,'files-joined-page');
  for(const field of ['value','knowledge','coverage'])assert.equal(field in emptySuffix,false,'suffix cannot be a generic full result');
  const negative=await sdk.listFolderPage({...args,search:'no-match'});
  const negativeEnd=await sdk.listFolderPage({...args,search:'no-match',continuation:negative.continuation});
  assert.equal(negativeEnd.retainedSoFar,'0');assert.equal(negativeEnd.queryAbsent,true);assert.equal(negativeEnd.queryKnowledge,'ABSENT');
  const pageSelector=new e.Interface(manifest.contracts.joined.abi).getFunction('readPage').selector;
  const unavailable=createFilesCompactSdk({ethers:e,manifest,rpc:(method,params)=>{if(method==='eth_call'&&params[0].data.startsWith(pageSelector))throw Error('joined read unavailable');return rpc(method,params);}});
  const unknown=await unavailable.listFolderPage({authors,context:await unavailable.pin()});
  assert.equal(unknown.kind,'files-joined-page');assert.equal(unknown.queryCoverage,'UNKNOWN');assert.equal(unknown.queryAbsent,false);
  for(const field of ['value','knowledge','coverage'])assert.equal(field in unknown,false,'UNKNOWN cannot be a generic empty result');
  for(const changes of [{authors:[...authors].reverse()},{tagScope:'revision'},{concept:e.id('other')},{search:'a'},{policy:'no-tiebreak'},{context:await sdk.pin()}])
    await assert.rejects(sdk.listFolderPage({...args,continuation:first.continuation,...changes}),/CONTINUATION/);
  const cold=createFilesCompactSdk({ethers:e,manifest,rpc});
  await assert.rejects(cold.listFolderPage({...args,context:await cold.pin(),continuation:first.continuation}),/CONTINUATION/);
  await assert.rejects(sdk.listFolderPage({...args,budget:0}),/BUDGET/);
  await run('edit',{file:file.file,document:'y'.repeat(41)});
  const pinned=await sdk.listFolderPage({...args,continuation:first.continuation});assert.equal(pinned.pageRows[0].file,directory.file);
  const changed=await sdk.listFolderPage({...args,budget:16,context:await sdk.pin(),tagScope:'revision'});
  assert.equal(changed.pageRows.length,0,'selected revision tag does not carry to new HEAD; directory branch is not applicable');
  const folderPurpose=e.id('efs2/purpose/folder/1');
  await env.transact('ledger','bind',[folderPurpose,manifest.folder,e.id('b-dir'),directory.file,0],'lower-directory','bob');
  await env.transact('ledger','unbind',[folderPurpose,manifest.folder,e.id('b-dir'),1],'mask-directory','alice');
  const maskedContext=await sdk.pin(),maskedFirst=await sdk.listFolderPage({authors,context:maskedContext,budget:1});
  const maskedSuffix=await sdk.listFolderPage({authors,context:maskedContext,budget:1,continuation:maskedFirst.continuation});
  assert.equal(maskedSuffix.pageRows.length,0);assert.equal(maskedSuffix.scannedSoFar,'2');assert.equal(maskedSuffix.retainedSoFar,'1');assert.equal(maskedSuffix.queryAbsent,false);
  await env.transact('ledger','bind',[folderPurpose,manifest.folder,e.id('a.txt'),file.file,0],'lower-file','bob');
  await env.transact('ledger','unbind',[folderPurpose,manifest.folder,e.id('a.txt'),1],'mask-file','alice');
  const allMaskedContext=await sdk.pin(),allMasked=await sdk.listFolderPage({authors,context:allMaskedContext,budget:1});
  assert.equal(allMasked.pageRows.length,0);assert.equal(allMasked.queryAbsent,false);
  const allMaskedEnd=await sdk.listFolderPage({authors,context:allMaskedContext,budget:1,continuation:allMasked.continuation});
  assert.equal(allMaskedEnd.retainedSoFar,'0');assert.equal(allMaskedEnd.scannedSoFar,'2');assert.equal(allMaskedEnd.queryAbsent,true);
});
test('failed Name-coordinate read preserves successful placement provenance',{timeout:120000},async t=>{
  const env=await createEnvironment(profile);t.after(()=>env.close());
  const {ethers:e,manifest,rpc,wallets}=env,authors=Object.values(manifest.authors);
  const sdk=createFilesCompactSdk({ethers:e,manifest,rpc,journal:await env.createJournal('partial')});
  const plan=await sdk.prepare({operation:'create',author:wallets.alice.address,authors,name:'known.txt',salt:e.id('known'),document:'known'});
  const signed=await sdk.authorize(plan,d=>wallets.alice.signingKey.sign(d).serialized);await sdk.submit(signed,tx=>env.send('create',tx,'alice'));
  const iface=new e.Interface(manifest.contracts.ledger.abi),selector=iface.getFunction('positionCell').selector;
  const broken=createFilesCompactSdk({ethers:e,manifest,rpc:(m,p)=>{if(m==='eth_call'&&p[0].data.startsWith(selector))throw Error('Name coordinate unavailable');return rpc(m,p);}});
  const partial=await broken.readPlacement({name:'known.txt',authors,context:await broken.pin()});
  assert.equal(partial.coverage,'PARTIAL');assert.equal(partial.knowledge,'UNKNOWN');
  assert.equal(partial.value.target,plan.file,'known selected target survives Name failure');
  assert.equal(partial.value.selection.status,1);assert.equal(partial.value.selection.author,e.zeroPadValue(wallets.alice.address,32));
  assert.equal(partial.value.kind,'file');assert.equal(partial.value.name.knowledge,'UNKNOWN');
});
