[profile.default]
src = "src"
test = "solidity-test"
out = "out"
libs = []
allow_paths = [".."]
remappings = ["C0Core/=../2026-09-05-c0-core/src/", "C0Admission/=../2026-09-05-c0-admission/src/"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
